# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/126/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/126/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/aaron/Documents/School/CIS 427/P1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/aaron/Documents/School/CIS 427/P1"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/126/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/126/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/aaron/Documents/School/CIS 427/P1/CMakeFiles" "/home/aaron/Documents/School/CIS 427/P1/CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/aaron/Documents/School/CIS 427/P1/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named P1_client

# Build rule for target.
P1_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 P1_client
.PHONY : P1_client

# fast build rule for target.
P1_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/build
.PHONY : P1_client/fast

#=============================================================================
# Target rules for targets named P1_server

# Build rule for target.
P1_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 P1_server
.PHONY : P1_server

# fast build rule for target.
P1_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/build
.PHONY : P1_server/fast

#=============================================================================
# Target rules for targets named P1_tests

# Build rule for target.
P1_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 P1_tests
.PHONY : P1_tests

# fast build rule for target.
P1_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/build
.PHONY : P1_tests/fast

main_client.o: main_client.cpp.o

.PHONY : main_client.o

# target to build an object file
main_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/main_client.cpp.o
.PHONY : main_client.cpp.o

main_client.i: main_client.cpp.i

.PHONY : main_client.i

# target to preprocess a source file
main_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/main_client.cpp.i
.PHONY : main_client.cpp.i

main_client.s: main_client.cpp.s

.PHONY : main_client.s

# target to generate assembly for a file
main_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/main_client.cpp.s
.PHONY : main_client.cpp.s

main_server.o: main_server.cpp.o

.PHONY : main_server.o

# target to build an object file
main_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/main_server.cpp.o
.PHONY : main_server.cpp.o

main_server.i: main_server.cpp.i

.PHONY : main_server.i

# target to preprocess a source file
main_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/main_server.cpp.i
.PHONY : main_server.cpp.i

main_server.s: main_server.cpp.s

.PHONY : main_server.s

# target to generate assembly for a file
main_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/main_server.cpp.s
.PHONY : main_server.cpp.s

src/client.o: src/client.cpp.o

.PHONY : src/client.o

# target to build an object file
src/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/src/client.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/client.cpp.o
.PHONY : src/client.cpp.o

src/client.i: src/client.cpp.i

.PHONY : src/client.i

# target to preprocess a source file
src/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/src/client.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/client.cpp.i
.PHONY : src/client.cpp.i

src/client.s: src/client.cpp.s

.PHONY : src/client.s

# target to generate assembly for a file
src/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_client.dir/build.make CMakeFiles/P1_client.dir/src/client.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/client.cpp.s
.PHONY : src/client.cpp.s

src/quotedb.o: src/quotedb.cpp.o

.PHONY : src/quotedb.o

# target to build an object file
src/quotedb.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/src/quotedb.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/quotedb.cpp.o
.PHONY : src/quotedb.cpp.o

src/quotedb.i: src/quotedb.cpp.i

.PHONY : src/quotedb.i

# target to preprocess a source file
src/quotedb.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/src/quotedb.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/quotedb.cpp.i
.PHONY : src/quotedb.cpp.i

src/quotedb.s: src/quotedb.cpp.s

.PHONY : src/quotedb.s

# target to generate assembly for a file
src/quotedb.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/src/quotedb.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/quotedb.cpp.s
.PHONY : src/quotedb.cpp.s

src/server.o: src/server.cpp.o

.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/src/server.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i

.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/src/server.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s

.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_server.dir/build.make CMakeFiles/P1_server.dir/src/server.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

tests/catch_config_main.o: tests/catch_config_main.cpp.o

.PHONY : tests/catch_config_main.o

# target to build an object file
tests/catch_config_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/tests/catch_config_main.cpp.o
.PHONY : tests/catch_config_main.cpp.o

tests/catch_config_main.i: tests/catch_config_main.cpp.i

.PHONY : tests/catch_config_main.i

# target to preprocess a source file
tests/catch_config_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/tests/catch_config_main.cpp.i
.PHONY : tests/catch_config_main.cpp.i

tests/catch_config_main.s: tests/catch_config_main.cpp.s

.PHONY : tests/catch_config_main.s

# target to generate assembly for a file
tests/catch_config_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/tests/catch_config_main.cpp.s
.PHONY : tests/catch_config_main.cpp.s

tests/quotedb_test.o: tests/quotedb_test.cpp.o

.PHONY : tests/quotedb_test.o

# target to build an object file
tests/quotedb_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/tests/quotedb_test.cpp.o
.PHONY : tests/quotedb_test.cpp.o

tests/quotedb_test.i: tests/quotedb_test.cpp.i

.PHONY : tests/quotedb_test.i

# target to preprocess a source file
tests/quotedb_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/tests/quotedb_test.cpp.i
.PHONY : tests/quotedb_test.cpp.i

tests/quotedb_test.s: tests/quotedb_test.cpp.s

.PHONY : tests/quotedb_test.s

# target to generate assembly for a file
tests/quotedb_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/P1_tests.dir/build.make CMakeFiles/P1_tests.dir/tests/quotedb_test.cpp.s
.PHONY : tests/quotedb_test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... P1_client"
	@echo "... P1_server"
	@echo "... P1_tests"
	@echo "... main_client.o"
	@echo "... main_client.i"
	@echo "... main_client.s"
	@echo "... main_server.o"
	@echo "... main_server.i"
	@echo "... main_server.s"
	@echo "... src/client.o"
	@echo "... src/client.i"
	@echo "... src/client.s"
	@echo "... src/quotedb.o"
	@echo "... src/quotedb.i"
	@echo "... src/quotedb.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... tests/catch_config_main.o"
	@echo "... tests/catch_config_main.i"
	@echo "... tests/catch_config_main.s"
	@echo "... tests/quotedb_test.o"
	@echo "... tests/quotedb_test.i"
	@echo "... tests/quotedb_test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

